force-app/main/default/objects/Order/fields/OrderConfirmationStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderConfirmationStatus__c</fullName>
    <label>Order Confirmation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Activation</fullName>
                <default>true</default>
                <label>Pending Activation</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderConfirmationQueue__c/OrderConfirmationQueue__c.object-meta.xml
<CustomObject>
    <label>Order Confirmation Queue Item</label>
    <nameField>
        <displayFormat>OC-{000000000}</displayFormat>
        <label>OrderConfirmationQueue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Confirmation Queue Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderConfirmationQueue__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OrderConfirmationQueue__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>OrderConfirmationQueueItems</relationshipLabel>
    <relationshipName>OrderConfirmationQueueItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderConfirmationQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderConfirmationGateway.cls
/**
 * Created by user on 9/15/23.
 */

public with sharing class OrderConfirmationGateway {

    public static void registerOrder(Id orderId) {
        try {
            Order order = OrderManager.getOrderById(orderId);

            if (order.Status != KPNConstants.ORDER_STATUS_ACTIVATED) {
                throw new OrderConfirmationGatewayException('Error: Only orders with status "Activated" will be accepted');
            }
            List<OrderItem> orderItems = OrderManager.getOrderItemsByOrderId(orderId);

            String confirmationData = buildOrderConfirmationJson(order, orderItems);
            updateOrderConfirmationStatusOnOrder(order);
            createAndSaveOrderConfirmationQueueItem(order, confirmationData);
        } catch (Exception e) {
            throw e;
        }
    }

    private static void updateOrderConfirmationStatusOnOrder(Order order) {
        order.OrderConfirmationStatus__c = KPNConstants.ORDER_CONFIRMATION_STATUS_IN_PROGRESS;
        update order;
    }

    private static String buildOrderConfirmationJson(Order order, List<OrderItem> orderItems) {
        OrderConfirmation data = new OrderConfirmation();
        data.accountNumber = order.Account.AccountNumber;
        data.orderNumber = order.OrderNumber;
        data.type = order.Type;
        data.status = order.Status;
        data.orderProducts = new List<OrderConfirmation.OrderProduct>();

        for (OrderItem orderItem : orderItems) {
            OrderConfirmation.OrderProduct orderProduct = new OrderConfirmation.OrderProduct();
            orderProduct.name = orderItem.Product2.Name;
            orderProduct.code = orderItem.Product2.ProductCode;
            orderProduct.unitPrice = orderItem.UnitPrice;
            orderProduct.quantity = Integer.valueOf(orderItem.Quantity);
            data.orderProducts.add(orderProduct);
        }
        return JSON.serializePretty(data, false);
    }

    private static void createAndSaveOrderConfirmationQueueItem(Order order, String confirmationData) {
        OrderConfirmationQueue__c queueItem = new OrderConfirmationQueue__c(
            Order__c = order.Id,
            Status__c = KPNConstants.ORDER_CONFIRMATION_QUEUE_ITEM_STATUS_NEW,
            Data__c = confirmationData
        );
        insert queueItem;
    }

    public class OrderConfirmationGatewayException extends Exception {}
}