force-app/main/default/objects/Order/fields/OrderConfirmationStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderConfirmationStatus__c</fullName>
    <label>Order Confirmation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Activation</fullName>
                <default>true</default>
                <label>Pending Activation</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderConfirmationEndpoint__mdt/OrderConfirmationEndpoint__mdt.object-meta.xml
<CustomObject>
    <label>Order Confirmation Endpoint</label>
    <pluralLabel>Order Confirmation Endpoints</pluralLabel>
</CustomObject>

force-app/main/default/objects/OrderConfirmationEndpoint__mdt/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>End Point</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderConfirmationEndpoint__mdt/fields/MaxDeliveryAttempts__c.field-meta.xml
<CustomField>
    <fullName>MaxDeliveryAttempts__c</fullName>
    <label>Max Delivery Attempts</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderConfirmationQueue__c/OrderConfirmationQueue__c.object-meta.xml
<CustomObject>
    <label>Order Confirmation Queue Item</label>
    <nameField>
        <displayFormat>OC-{000000000}</displayFormat>
        <label>OrderConfirmationQueue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Confirmation Queue Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderConfirmationQueue__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OrderConfirmationQueue__c/fields/DeliveryAttemptCount__c.field-meta.xml
<CustomField>
    <fullName>DeliveryAttemptCount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Delivery Attempt Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderConfirmationQueue__c/fields/LastResponseMessage__c.field-meta.xml
<CustomField>
    <fullName>LastResponseMessage__c</fullName>
    <label>Last Response Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OrderConfirmationQueue__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>OrderConfirmationQueueItems</relationshipLabel>
    <relationshipName>OrderConfirmationQueueItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderConfirmationQueue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderConfirmationQueueJob.cls
/**
 * Created by user on 9/16/23.
 */

public class OrderConfirmationQueueJob implements Database.Batchable<SObject>, Database.AllowsCallouts {

    public String query = 'SELECT Id, Order__c, DeliveryAttemptCount__c, Data__c FROM OrderConfirmationQueue__c WHERE Status__c NOT IN :queueItemStatusList LIMIT 10';

    public Database.QueryLocator start(Database.BatchableContext bc) {
        List<String> queueItemStatusList = new List<String> {
            KPNConstants.ORDER_CONFIRMATION_QUEUE_ITEM_STATUS_FAILED,
            KPNConstants.ORDER_CONFIRMATION_QUEUE_ITEM_STATUS_COMPLETED
        };
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<OrderConfirmationQueue__c> scope) {
        OrderConfirmationEndpoint__mdt endpointConfig = getEndpointConfig(KPNConstants.ENDPOINT_DEVELOPERNAME_ORDER_CONFIRMATION_GENERIC);
        
        List<Order> ordersToUpdate = new List<Order>();
        List<OrderConfirmationQueue__c> queueItemsToUpdate = new List<OrderConfirmationQueue__c>();

        for (OrderConfirmationQueue__c queueItem : scope) {
            HttpResponse response = sendConfirmationCallout(endpointConfig.EndPoint__c, queueItem.Data__c);

            queueItem.LastResponseMessage__c = response.toString();
            queueItem.DeliveryAttemptCount__c += 1;

            Order order = new Order(Id = queueItem.Order__c);

            // handle success response
            if (response.getStatusCode() == KPNConstants.HTTP_STATUS_CODE_OK) {
                queueItem.Status__c = KPNConstants.ORDER_CONFIRMATION_QUEUE_ITEM_STATUS_COMPLETED;
                order.OrderConfirmationStatus__c = KPNConstants.ORDER_CONFIRMATION_STATUS_DELIVERED;
                ordersToUpdate.add(order);
            } else {
                // handle errors
                if (queueItem.DeliveryAttemptCount__c < endpointConfig.MaxDeliveryAttempts__c) {
                    queueItem.Status__c = KPNConstants.ORDER_CONFIRMATION_QUEUE_ITEM_STATUS_RETRY;
                } else {
                    // could not deliver order confirmation
                    queueItem.Status__c = KPNConstants.ORDER_CONFIRMATION_QUEUE_ITEM_STATUS_FAILED;
                    order.OrderConfirmationStatus__c = KPNConstants.ORDER_CONFIRMATION_STATUS_FAILED;
                    ordersToUpdate.add(order);
                }
            }
            queueItemsToUpdate.add(queueItem);
        }
        update queueItemsToUpdate;
        update ordersToUpdate;
    }

    public void finish(Database.BatchableContext bc) {}

    public HttpResponse sendConfirmationCallout(String endpoint, String payload) {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(endpoint);
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json');
        request.setBody(payload);

        return http.send(request);
    }

    public OrderConfirmationEndpoint__mdt getEndpointConfig(String developerName) {
        List<OrderConfirmationEndpoint__mdt> endpointConfig = [SELECT EndPoint__c, MaxDeliveryAttempts__c FROM OrderConfirmationEndpoint__mdt WHERE DeveloperName = :developerName LIMIT 1];

        if (endpointConfig.isEmpty()) {
            throw new IllegalArgumentException('Endpoint config developerName does not exist [' + developerName + ']');
        }
        return endpointConfig[0];
    }
}